name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Contribution Snake

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: DareDevil317
          outputs: dist/github-contribution-grid-snake.svg
          color_snake: "#FF0000"
          color_dots: "#161B22,#39D353,#26A641,#006D32,#0E4429"



      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
