name: Generate Dark Red Snake üêç

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every 24 hours
  workflow_dispatch:     # Allows manual run

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate dark-red snake
        uses: Platane/snk@v3
        with:
          github_user_name: DareDevil317
          outputs: dist/snake-dark-red.svg
          snake_color: "#e50914"
          background: "#0d1117"

      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
